package com.microaltech.bandirush;

/** Data semua level. Peta ditulis dari garis finish (atas) ke titik awal (bawah). Legenda ada di {@link Level}. */
final class Levels {
    private Levels() {
    }

    static final Level.Def[] ALL = {
            new Level.Def("1. Hutan Wumpa", Theme.JUNGLE, Level.MODE_NORMAL, Music.JUNGLE, 24f,
                    "Tombol X lompat, O putar. Injak atau putar peti!",
                    "  G  ",
                    " ... ",
                    ".....",
                    "W.W.W",
                    ".C?C.",
                    ".....",
                    "..H..",
                    ".....",
                    ".....",
                    "  .  ",
                    "  w  ",
                    "  w  ",
                    "  .  ",
                    "..B..",
                    ".....",
                    "W...W",
                    ".C.C.",
                    ".....",
                    "E....",
                    ".....",
                    ".W.W.",
                    ".....",
                    "..K..",
                    ".....",
                    "..T..",
                    ".....",
                    ".C.L.",
                    ".....",
                    "  .  ",
                    "  m  ",
                    "     ",
                    "  m  ",
                    "  .  ",
                    ".....",
                    "..A..",
                    ".....",
                    "....E",
                    ".....",
                    "CWIWC",
                    ".....",
                    " ... ",
                    " .W. ",
                    "  .  ",
                    "  W  ",
                    "  .  ",
                    " ... ",
                    ".....",
                    "..C..",
                    ".....",
                    "E....",
                    ".....",
                    ".W.W.",
                    ".....",
                    "..?..",
                    ".....",
                    ".....",
                    "..S..",
                    "....."),

            new Level.Def("2. Jembatan Senja", Theme.SUNSET, Level.MODE_NORMAL, Music.SUNSET, 26f,
                    "Tahan X saat mendarat di peti pantul untuk lompat lebih tinggi.",
                    "  G  ",
                    " ... ",
                    ".....",
                    ".W?W.",
                    ".....",
                    "H...H",
                    ".....",
                    "  .  ",
                    "  i  ",
                    "     ",
                    "  i  ",
                    "     ",
                    "  i  ",
                    "  .  ",
                    ".....",
                    "..K..",
                    ".....",
                    ".....",
                    "  .  ",
                    "  w  ",
                    "     ",
                    "     ",
                    "  b  ",
                    "  .  ",
                    ".....",
                    "T.W.T",
                    ".....",
                    ".C.C.",
                    ".....",
                    "  .  ",
                    "  m  ",
                    "     ",
                    "  m  ",
                    "     ",
                    "  m  ",
                    "  .  ",
                    ".....",
                    "..A..",
                    ".....",
                    "E....",
                    ".....",
                    "  .  ",
                    "  w  ",
                    "     ",
                    "  w  ",
                    "  .  ",
                    ".....",
                    ".?.C.",
                    ".....",
                    "..W..",
                    "..W..",
                    ".....",
                    "..S..",
                    "....."),

            new Level.Def("3. Kuil TNT", Theme.TEMPLE, Level.MODE_NORMAL, Music.TEMPLE, 26f,
                    "Jangan sentuh Nitro hijau! TNT meledak 3 detik setelah diinjak.",
                    "   G   ",
                    "  ...  ",
                    ".......",
                    "W.W?W.W",
                    ".......",
                    ".N.T.N.",
                    ".......",
                    "H.....H",
                    ".......",
                    "   .   ",
                    "   i   ",
                    "       ",
                    "  i    ",
                    "       ",
                    "    i  ",
                    "       ",
                    "   i   ",
                    "   .   ",
                    ".......",
                    "..K....",
                    ".......",
                    "NN.T.NN",
                    ".......",
                    "...E...",
                    ".......",
                    "  ...  ",
                    "   m   ",
                    "       ",
                    "   m   ",
                    "       ",
                    "   m   ",
                    "  ...  ",
                    ".......",
                    ".C.A.C.",
                    ".......",
                    "T..W..T",
                    ".......",
                    "...B...",
                    ".......",
                    "  ...  ",
                    ".......",
                    "E.....E",
                    ".......",
                    ".C?.?C.",
                    ".......",
                    "..W.W..",
                    ".......",
                    "...S...",
                    "......."),

            new Level.Def("4. Puncak Salju", Theme.SNOW, Level.MODE_NORMAL, Music.SNOW, 24f,
                    "Tombol ▼ untuk meluncur. Meluncur + lompat = lompat jauh!",
                    "  G  ",
                    " ... ",
                    ".....",
                    "W3?3W",
                    ".....",
                    "UUUUU",
                    ".....",
                    ".W.W.",
                    ".....",
                    "E....",
                    ".....",
                    "  .  ",
                    "     ",
                    "     ",
                    "     ",
                    "     ",
                    "  .  ",
                    ".....",
                    "..K..",
                    ".....",
                    "  .  ",
                    "  O  ",
                    "     ",
                    "  O  ",
                    "     ",
                    "  O  ",
                    "  .  ",
                    ".o!o.",
                    ".....",
                    "2...2",
                    ".....",
                    "UUUUU",
                    ".....",
                    "..W..",
                    ".....",
                    ".3.3.",
                    ".....",
                    "....E",
                    ".....",
                    ".?.L.",
                    ".....",
                    "..S..",
                    "....."),

            new Level.Def("5. Kejaran Batu", Theme.JUNGLE, Level.MODE_CHASE, Music.CHASE, 14f,
                    "LARI! Batu raksasa mengejar dari belakang!",
                    "  G  ",
                    " ... ",
                    ".....",
                    ".....",
                    "W.W.W",
                    ".....",
                    "  .  ",
                    "     ",
                    "  .  ",
                    ".....",
                    "N...N",
                    ".....",
                    ".C.C.",
                    ".....",
                    "  .  ",
                    "  w  ",
                    "  .  ",
                    ".....",
                    "..K..",
                    ".....",
                    "W...W",
                    ".....",
                    " ... ",
                    "     ",
                    " ... ",
                    ".....",
                    "..C..",
                    ".....",
                    "N.W.N",
                    ".....",
                    ".....",
                    "  .  ",
                    "     ",
                    "  .  ",
                    ".....",
                    "W.W.W",
                    ".....",
                    "..C..",
                    ".....",
                    ".....",
                    "..S..",
                    ".....",
                    ".....",
                    "....."),

            new Level.Def("6. Raja Kepiting", Theme.BEACH, Level.MODE_BOSS, Music.BOSS, 40f,
                    "Hindari bom! Saat bos pusing, putar atau injak dia.",
                    "   X   ",
                    ".......",
                    ".......",
                    ".......",
                    ".......",
                    ".......",
                    ".......",
                    ".......",
                    ".......",
                    ".......",
                    ".W...W.",
                    ".......",
                    "...A...",
                    ".......",
                    "...S...",
                    ".......")
    };
}
