package com.microaltech.bandirush;

/** Data semua level. Peta ditulis dari garis finish (atas) ke titik awal (bawah). Legenda ada di {@link Level}. */
final class Levels {
    private Levels() {
    }

    static final Level.Def[] ALL = {
            new Level.Def("Tutorial", Theme.JUNGLE, Level.MODE_NORMAL, Music.JUNGLE, 60f,
                    "Ikuti petunjuk di atas layar.",
                    "  G  ",
                    " ... ",
                    ".....",
                    ".....",
                    "  .  ",
                    "  O  ",
                    "     ",
                    "  O  ",
                    "  .  ",
                    "..!..",
                    ".....",
                    ".....",
                    "..A..",
                    ".....",
                    "..K..",
                    ".....",
                    ".....",
                    "N...N",
                    ".....",
                    ".....",
                    "..T..",
                    ".....",
                    ".....",
                    "  .  ",
                    "     ",
                    "     ",
                    "     ",
                    "     ",
                    "  .  ",
                    ".....",
                    "UUUUU",
                    ".....",
                    ".....",
                    ".....",
                    "..B..",
                    ".....",
                    ".....",
                    "E....",
                    ".....",
                    ".....",
                    ".C.C.",
                    ".....",
                    ".....",
                    ".....",
                    "..C..",
                    ".....",
                    ".....",
                    "     ",
                    ".....",
                    ".....",
                    ".....",
                    ".....",
                    ".W.W.",
                    ".....",
                    ".....",
                    "..S..",
                    ".....")
                    .tips(
                    "1:Selamat datang! Dorong joystick kiri ke atas untuk berlari.",
                    "6:Ambil buah wumpa. 100 wumpa = 1 nyawa, dan wumpa bisa dibelanjakan di Toko!",
                    "10:Tekan X untuk melompati jurang. Tahan X untuk lompat lebih tinggi.",
                    "12:Lompat ke atas peti untuk menghancurkannya.",
                    "15:Tekan O untuk berputar dan menghancurkan peti di sekitarmu.",
                    "18:Putar atau injak musuh untuk mengalahkannya!",
                    "21:Peti pantul melempar tinggi. Tahan X saat mendarat untuk lebih tinggi.",
                    "24:Tekan tombol \u25BC untuk meluncur di bawah palang.",
                    "28:Jurang lebar: meluncur lalu lompat = lompat jauh! Atau tekan O di udara.",
                    "35:TNT meledak 3 detik setelah diinjak. Segera menjauh!",
                    "38:Nitro hijau meledak kalau disentuh. Jangan sampai kena!",
                    "41:Peti C = checkpoint. Peti A = topeng yang menahan 1 serangan.",
                    "46:Aktifkan peti ! untuk memunculkan pijakan di atas jurang.",
                    "54:Kristal di depan adalah garis finish. Kamu siap bertualang!")
                    .tutorial(),

            new Level.Def("1. Hutan Wumpa", Theme.JUNGLE, Level.MODE_NORMAL, Music.JUNGLE, 24f,
                    "Tombol X lompat, O putar. Injak atau putar peti!",
                    "  G  ",
                    " ... ",
                    ".....",
                    "W.W.W",
                    ".C?C.",
                    ".....",
                    "..H..",
                    ".....",
                    ".....",
                    "  .  ",
                    "  w  ",
                    "  w  ",
                    "  .  ",
                    "..B..",
                    ".....",
                    "W...W",
                    ".C.C.",
                    ".....",
                    "E....",
                    ".....",
                    ".W.W.",
                    ".....",
                    "..K..",
                    ".....",
                    "..T..",
                    ".....",
                    ".CPL.",
                    ".....",
                    "  .  ",
                    "  m  ",
                    "     ",
                    "  m  ",
                    "  .  ",
                    ".....",
                    "..A..",
                    ".....",
                    "....E",
                    ".....",
                    "CWIWC",
                    ".....",
                    " ... ",
                    " .W. ",
                    "  .  ",
                    "  W  ",
                    "  .  ",
                    " ... ",
                    ".....",
                    "..C..",
                    ".....",
                    "E....",
                    ".....",
                    ".W.W.",
                    ".....",
                    "..?..",
                    ".....",
                    ".....",
                    "..S..",
                    ".....")
                    .bonus(new Level.Def("Bonus Hutan", Theme.JUNGLE, Level.MODE_NORMAL, Music.JUNGLE, 0f,
                    "Hancurkan semua peti! Jatuh di sini tidak mengurangi nyawa.",
                    "  G  ",
                    " ... ",
                    ".2?2.",
                    ".....",
                    "  .  ",
                    "  b  ",
                    "     ",
                    "     ",
                    "  .  ",
                    ".C.C.",
                    ".3.3.",
                    ".....",
                    "C...C",
                    ".....",
                    "..S..",
                    ".....")),

            new Level.Def("2. Jembatan Senja", Theme.SUNSET, Level.MODE_NORMAL, Music.SUNSET, 26f,
                    "Tahan X saat mendarat di peti pantul untuk lompat lebih tinggi.",
                    "  G  ",
                    " ... ",
                    ".....",
                    ".W?W.",
                    ".....",
                    "H...H",
                    ".....",
                    "  .  ",
                    "  i  ",
                    "     ",
                    "  i  ",
                    "     ",
                    "  i  ",
                    "  .  ",
                    ".....",
                    "..K..",
                    ".....",
                    ".....",
                    "  .  ",
                    "  w  ",
                    "     ",
                    "     ",
                    "  b  ",
                    "  .  ",
                    ".....",
                    "T.W.T",
                    ".....",
                    ".C.C.",
                    ".....",
                    "  .  ",
                    "  m  ",
                    "     ",
                    "  m  ",
                    "     ",
                    "  m  ",
                    "  .  ",
                    ".....",
                    "..A..",
                    ".....",
                    "E....",
                    ".....",
                    "  .  ",
                    "  w  ",
                    "     ",
                    "  w  ",
                    "  .  ",
                    ".....",
                    ".?.C.",
                    ".....",
                    "..W..",
                    "..W..",
                    ".....",
                    "..S..",
                    "....."),

            new Level.Def("3. Kuil TNT", Theme.TEMPLE, Level.MODE_NORMAL, Music.TEMPLE, 26f,
                    "Jangan sentuh Nitro hijau! TNT meledak 3 detik setelah diinjak.",
                    "   G   ",
                    "  ...  ",
                    ".......",
                    "W.W?W.W",
                    ".......",
                    ".N.T.N.",
                    ".......",
                    "H.....H",
                    ".......",
                    "   .   ",
                    "   i   ",
                    "       ",
                    "  i    ",
                    "       ",
                    "    i  ",
                    "       ",
                    "   i   ",
                    "   .   ",
                    ".......",
                    "..K....",
                    ".......",
                    "NN.T.NN",
                    ".......",
                    "...E...",
                    ".......",
                    "  ...  ",
                    "   m   ",
                    "       ",
                    "   m   ",
                    "       ",
                    "   m   ",
                    "  ...  ",
                    ".......",
                    ".C.A.C.",
                    ".......",
                    "T..W..T",
                    ".......",
                    "...B...",
                    ".......",
                    "  ...  ",
                    ".......",
                    "E.....E",
                    ".......",
                    ".C?.?C.",
                    ".......",
                    "..W.W..",
                    ".......",
                    "...S...",
                    "......."),

            new Level.Def("4. Puncak Salju", Theme.SNOW, Level.MODE_NORMAL, Music.SNOW, 24f,
                    "Tombol ▼ untuk meluncur. Meluncur + lompat = lompat jauh!",
                    "  G  ",
                    " ... ",
                    ".....",
                    "W3?3W",
                    ".....",
                    "UUUUU",
                    ".....",
                    ".W.W.",
                    ".....",
                    "E....",
                    ".....",
                    "  .  ",
                    "     ",
                    "     ",
                    "     ",
                    "     ",
                    "  .  ",
                    ".....",
                    "..K..",
                    ".....",
                    "  .  ",
                    "  O  ",
                    "     ",
                    "  O  ",
                    "     ",
                    "  O  ",
                    "  .  ",
                    ".o!o.",
                    ".....",
                    "2.P.2",
                    ".....",
                    "UUUUU",
                    ".....",
                    "..W..",
                    ".....",
                    ".3.3.",
                    ".....",
                    "....E",
                    ".....",
                    ".?.L.",
                    ".....",
                    "..S..",
                    ".....")
                    .bonus(new Level.Def("Bonus Salju", Theme.SNOW, Level.MODE_NORMAL, Music.SNOW, 0f,
                    "Hancurkan semua peti! Jatuh di sini tidak mengurangi nyawa.",
                    "  G  ",
                    " ... ",
                    "W?W?W",
                    ".....",
                    "  .  ",
                    "  O  ",
                    "     ",
                    "  O  ",
                    "  .  ",
                    "..!..",
                    ".....",
                    ".2.2.",
                    ".....",
                    "..S..",
                    ".....")),

            new Level.Def("5. Tunggangan Babi", Theme.SUNSET, Level.MODE_RIDE, Music.CHASE, 12f,
                    "Babi berlari sendiri! Geser kiri-kanan, lompati jurang, hindari peti besi & Nitro.",
                    "  G  ",
                    " ... ",
                    ".....",
                    ".....",
                    ".....",
                    ".....",
                    ".....",
                    ".....",
                    "E...E",
                    ".....",
                    "     ",
                    "     ",
                    ".....",
                    "W.W.W",
                    ".....",
                    "..I..",
                    ".....",
                    ".LCC.",
                    ".....",
                    "I.W.I",
                    ".....",
                    "     ",
                    ".....",
                    "C...C",
                    ".....",
                    "..N..",
                    ".....",
                    "W.W.W",
                    ".....",
                    ".I.I.",
                    ".....",
                    "N...N",
                    ".....",
                    "..K..",
                    ".....",
                    "     ",
                    "     ",
                    ".....",
                    ".W.W.",
                    ".....",
                    "II.II",
                    ".....",
                    "E....",
                    ".....",
                    "C.W.C",
                    ".....",
                    "..I..",
                    ".....",
                    "     ",
                    ".....",
                    ".W.W.",
                    ".....",
                    "I...I",
                    ".....",
                    "..C..",
                    ".....",
                    ".W.W.",
                    ".....",
                    ".....",
                    ".....",
                    "..S..",
                    "....."),

            new Level.Def("6. Kejaran Batu", Theme.JUNGLE, Level.MODE_CHASE, Music.CHASE, 14f,
                    "LARI! Batu raksasa mengejar dari belakang!",
                    "  G  ",
                    " ... ",
                    ".....",
                    ".....",
                    "W.W.W",
                    ".....",
                    "  .  ",
                    "     ",
                    "  .  ",
                    ".....",
                    "N...N",
                    ".....",
                    ".C.C.",
                    ".....",
                    "  .  ",
                    "  w  ",
                    "  .  ",
                    ".....",
                    "..K..",
                    ".....",
                    "W...W",
                    ".....",
                    " ... ",
                    "     ",
                    " ... ",
                    ".....",
                    "..C..",
                    ".....",
                    "N.W.N",
                    ".....",
                    ".....",
                    "  .  ",
                    "     ",
                    "  .  ",
                    ".....",
                    "W.W.W",
                    ".....",
                    "..C..",
                    ".....",
                    ".....",
                    "..S..",
                    ".....",
                    ".....",
                    "....."),

            new Level.Def("7. Raja Kepiting", Theme.BEACH, Level.MODE_BOSS, Music.BOSS, 40f,
                    "Hindari bom! Saat bos pusing, putar atau injak dia.",
                    "   X   ",
                    ".......",
                    ".......",
                    ".......",
                    ".......",
                    ".......",
                    ".......",
                    ".......",
                    ".......",
                    ".......",
                    ".W...W.",
                    ".......",
                    "...A...",
                    ".......",
                    "...S...",
                    "......."),

            new Level.Def("8. Sungai Deras", Theme.RIVER, Level.MODE_NORMAL, Music.JUNGLE, 30f,
                    "Kayu apung tenggelam kalau diinjak terlalu lama. Awas piranha!",
                    "  G  ",
                    " ... ",
                    ".W?W.",
                    ".....",
                    "  .  ",
                    "  m  ",
                    "     ",
                    "  m  ",
                    "  .  ",
                    ".....",
                    ".T.T.",
                    ".....",
                    "  .  ",
                    "  Y  ",
                    "  w  ",
                    "  .  ",
                    ".....",
                    "W.W.W",
                    ".....",
                    "  .  ",
                    "  r  ",
                    " Y Y ",
                    "  r  ",
                    "     ",
                    "  r  ",
                    "  .  ",
                    ".....",
                    "..K..",
                    ".....",
                    ".C?C.",
                    ".....",
                    "E....",
                    ".....",
                    "  .  ",
                    "  m  ",
                    "  Y  ",
                    "  m  ",
                    "  .  ",
                    ".....",
                    "..C..",
                    ".....",
                    "  .  ",
                    "  r  ",
                    "Y   Y",
                    "  r  ",
                    "  .  ",
                    ".....",
                    ".W.W.",
                    ".....",
                    "..S..",
                    ".....")
                    .water(),

            new Level.Def("9. Gua Gelap", Theme.CAVE, Level.MODE_NORMAL, Music.TEMPLE, 30f,
                    "Gelap gulita! Kelelawar terbang rendah: meluncur di bawahnya atau putar.",
                    "  G  ",
                    " ... ",
                    ".W.W.",
                    ".....",
                    ".A...",
                    ".....",
                    "N.V.N",
                    ".....",
                    "     ",
                    "     ",
                    ".....",
                    ".?.?.",
                    ".....",
                    "UUUUU",
                    ".....",
                    "..V..",
                    ".....",
                    "  .  ",
                    "  i  ",
                    "     ",
                    "  i  ",
                    "  .  ",
                    ".....",
                    "..K..",
                    ".....",
                    ".3.3.",
                    ".....",
                    "V...V",
                    ".....",
                    "..T..",
                    ".....",
                    "..V..",
                    ".....",
                    "     ",
                    ".....",
                    ".C.C.",
                    ".....",
                    "..V..",
                    ".....",
                    ".W.W.",
                    ".....",
                    "..S..",
                    ".....")
                    .dark(),

            new Level.Def("10. Gletser Licin", Theme.ICE, Level.MODE_NORMAL, Music.SNOW, 28f,
                    "Lantai es licin! Bandi susah berhenti. Awas pinguin yang meluncur.",
                    "  G  ",
                    " ... ",
                    "W.W.W",
                    ".....",
                    "T...T",
                    ".....",
                    "  .  ",
                    "  .  ",
                    "  .  ",
                    ".....",
                    ".2?2.",
                    ".....",
                    "  .  ",
                    "  m  ",
                    "     ",
                    "  m  ",
                    "  .  ",
                    ".....",
                    "J...J",
                    ".....",
                    "..K..",
                    ".....",
                    "  .  ",
                    "  i  ",
                    "     ",
                    "  i  ",
                    "  .  ",
                    ".....",
                    ".....",
                    "J....",
                    ".....",
                    "C.C.C",
                    ".....",
                    "  .  ",
                    "     ",
                    "  .  ",
                    ".....",
                    "..J..",
                    ".....",
                    ".W.W.",
                    ".....",
                    "..S..",
                    ".....")
                    .ice()
    };

    /** Jumlah level yang dihitung untuk kristal & relik (tanpa tutorial). */
    static int progressCount() {
        int n = 0;
        for (Level.Def d : ALL) if (!d.tutorial) n++;
        return n;
    }

    static int indexOfMode(int mode) {
        for (int i = 0; i < ALL.length; i++) if (ALL[i].mode == mode) return i;
        return -1;
    }
}
